<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<form id="btn_sub" action="{{url('admin/state_tab2_save')}}" method="POST" enctype="multipart/form-data">
@csrf
<div class="form-group">
	<input type="hidden" name="id" value="{{$id}}">
    <label for="inputAddress"><b><h1>Section1</b></h1></label>
	<div class="text1" contenteditable="true">
		@if($k==0)
	        <div class="ad_tabber_contents_item widget_1613735646530_2_1" data-id="widget_1613735646530_2" data-scrollid="widget_1613735646530_2">





	            <div class="ad_tabber_contents_item_rich_text" style="margin-top: 24px; margin-bottom: 0px;">
	                <h3 style="margin-bottom: 24px;">Subchapter or Small Business Corporation (S Corporation or S Corp)</h3>
	                <p style="margin-bottom: 40px;">The S Corporation, or S Corp, is a business entity that was created and enacted into law by Congress in 1958. It was created to encourage small and family business
	                    creation, while eliminating the double taxation that conventional corporations (C Corps) had to pay. Key factors for S Corps include:</p>
	            </div>




	        </div>





	        <div class="ad_tabber_contents_item widget_1613735646530_2_2" data-id="widget_1613735646530_2">




	            <div class="ad_tabber_contents_item_boxed_content">
	                <div class="boxed-content-container">

	                    <div class="boxed-color-box">

	                        <ul>
	                            <li style="margin-bottom: 16px;">S Corps are formed and regulated on a state level.</li>
	                            <li style="margin-bottom: 16px;">The liability of the S Corp and the personal liability of the owners and investors are separate.</li>
	                            <li style="margin-bottom: 16px;">The liability of the owners and investors in an S Corp is limited only to the value of their investment.</li>
	                            <li style="margin-bottom: 16px;">The owners of a corporation are not personally liable for business debts, claims, or other liabilities.</li>
	                            <li style="margin-bottom: 16px;">There are some more legalities, rules, and compliance for an S Corp than an LLC.</li>
	                            <li style="margin-bottom: 16px;">An S Corp has a slightly more complex corporate structure.</li>
	                            <li style="margin-bottom: 16px;">S Corps are limited to having 100 shareholders.</li>
	                            <li>Running an S Corp is simpler and easier than running a C Corp.</li>
	                        </ul>

	                    </div>
	                </div>

	            </div>



	        </div>





	        <div class="ad_tabber_contents_item widget_1613735646530_2_3" data-id="widget_1613735646530_2">





	            <div class="ad_tabber_contents_item_rich_text" style="margin-top: 0px; margin-bottom: 0px;">
	                <p style="margin-bottom: 48px;">The cost and policies governing an LLC do vary from state to state. Check out our <a href="llc-state-information.html" rel="noopener">LLC State Information</a> resource
	                    for additional info on your state.</p>
	                <h3 style="margin-bottom: 24px;">S Corporation Taxes and Tax Returns</h3>
	                <p style="margin-bottom: 32px;">Unlike traditional C Corporations, the S Corporation does not need to pay corporate income tax. The S Corporation is a separate tax designation recognized by the IRS.
	                    Similar to the LLC, the net profit or loss generated by an S Corporation will flow through to the personal income tax returns of the shareholders and owners, and
	                    be subject to tax there.</p>
	                <p style="margin-bottom: 48px;">As with LLCs, an S Corp will have to pay certain other types of taxes like payroll, property and sales tax on business purchases.</p>
	                <h3 style="margin-bottom: 24px;">Forming an LLC but Paying Tax as an S Corp</h3>
	                <p style="margin-bottom: 40px;">When you create an LLC, you may have the option to choose to be treated as an S Corp for taxation purposes. This takes advantage of both business types, as follows:</p>
	            </div>




	        </div>





	        <div class="ad_tabber_contents_item widget_1613735646530_2_4" data-id="widget_1613735646530_2">




	            <div class="ad_tabber_contents_item_boxed_content">
	                <div class="boxed-content-container">

	                    <div class="boxed-color-box">

	                        <ul>
	                            <li style="margin-bottom: 16px;">The rules and regulations for running an LLC are less onerous than running an S Corp.</li>
	                            <li style="margin-bottom: 16px;">There may be tax advantages to being taxed as an S Corp, specifically around owners and members taking money out of the business.</li>
	                            <li>You can choose to pay yourself a “reasonable” salary and deduct monies above that as share dividend income. That additional income would not be subject
	                                to self-employment tax, although it would still be subject to personal income tax.</li>
	                        </ul>

	                    </div>
	                </div>

	            </div>



	        </div>





	        <div class="ad_tabber_contents_item widget_1613735646530_2_5 last-item" data-id="widget_1613735646530_2">





	            <div class="ad_tabber_contents_item_rich_text" style="margin-top: 0px; margin-bottom: 0px;">
	                <p style="margin: 0;">If you're interested in how to save additional money on taxes by filing your business as an S Corporation,<a style="font-weight: 900;" href="s-corporation-tax-calculator/index.html"
	                        target="_blank" rel="noopener"> check out our S Corporation Tax Calculator. </a></p>
	            </div>




	        </div>
	    @else
	    {!! $data->section1 !!}
	    @endif     


	</div>
	<textarea class="section1  d-none" name="section1"></textarea>
</div>

<button type="button" class="btn btn-primary">Update</button>
<button type="submit" class="btn btn-primary  d-none">Add Banner</button>
</form>

<script>
   $(document).ready(function(){
        
	    $(".btn").click(function(){
	      var txt1=$(".text1").html();
	      var txt2=$(".text2").html();
	      $(".section2").val(txt2);
	      $(".section1").val(txt1);
	      $("#btn_sub").submit();
	      

	   });
});
</script>